<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_FinalTest" Id="{f7c9b199-23a8-4316-8294-e5afe3220f77}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_FinalTest

VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="LeakTest" Id="{263c8cfe-7a2f-4231-b3e4-7f002a5e9e71}">
      <Declaration><![CDATA[METHOD PUBLIC LeakTest : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ModuleCheck" Id="{c89c3e22-89a6-41b9-b0f5-144d51810253}">
      <Declaration><![CDATA[METHOD PRIVATE ModuleCheck : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>